site_name: python-cfg
site_description: >-
  A decorator @cfg that selects a method implementation among those that are
  identically named on a class at class build time — leaving only the selected
  method in its attribute set.
site_url: https://jymchng.github.io/conditional-method/
repo_url: https://github.com/jymchng/conditional-method
repo_name: jymchng/conditional-method
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  features:
    - navigation.instant
    - content.code.copy
nav:
  - Home: index.md
  - Benchmarks: benchmarks.md
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
