FROM python:3.8-slim as py3.8
WORKDIR /app

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy application files
COPY src/ ./src/
COPY tests/ ./tests/
COPY noxfile.py ./
COPY README.md ./
COPY pyproject.toml ./

RUN python -m venv .venv && \
    python -m pip install uv && \
    python -m pip install nox && \
    export PATH=".venv/bin:$PATH" && \
    uv run nox -s dev && \
    deactivate

RUN echo "Built the package"

FROM python:3.8-slim as py3.8

# Change to the client directory
WORKDIR /client

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the distribution files and example script
COPY dist/ ./dist/
COPY tests/ ./tests/
COPY noxfile.py ./
COPY README.md ./
COPY pyproject.toml ./

RUN echo "========== CURRENT WORKING DIRECTORY FILES ===========" && \
    ls . && \
    echo "======================================================" && \
    echo "========== CURRENT WORKING DIRECTORY ===========" && \
    echo $PWD && \
    echo "================================================"

# Install the package from the distribution (tarfile)
RUN python -m venv .venv && \
    . .venv/bin/activate && \
    echo "========== PYTHON VERSION ===========" && \
    python --version && \
    echo "=====================================" && \
    python -m pip uninstall conditional-method -y && \
    python -m pip install dist/*.tar.gz && \
    python -m pip install pytest>=8.3.4  && \
    python -m pip freeze && \
    python -m pytest tests -s -vv && \
    deactivate

# Install the package from the distribution (wheel)
RUN python -m venv .venv && \
    . .venv/bin/activate && \
    echo "========== PYTHON VERSION ===========" && \
    python --version && \
    echo "=====================================" && \
    python -m pip uninstall conditional-method -y && \
    python -m pip install dist/*.whl && \
    python -m pip install pytest>=8.3.4  && \
    python -m pip freeze && \
    python -m pytest tests -s -vv && \
    deactivate

# Set the default command to execute when the container starts
CMD ["echo", "all tests done"]